# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 373823c451ea46050b55293899639363e381976733d687abe63437acb5d701a8815bcd58643d56b9c8b6ca0ac81b5fc4fc03aa78bcf9dcd41d9579cd3bb467fd

test:
  secret_key_base: 4508a402441813050f9c95da0afe5648b6569ac8764bcd861b4e4b62c425e7633456971fa0bf1d081fed1e5512f03e395493cf1a38d4c66b120e35798dcfda28

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
